apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.settings.name }}-{{ .Values.settings.env }}-cert
  labels:
    app.kubernetes.io/name: {{ .Values.settings.name }}
    app.kubernetes.io/part-of: {{ .Values.settings.name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:  
  secret: {{ .Values.php.secret | default (randAlphaNum 40) | b64enc | quote }}
  mercure-jwt-secret: {{ .Values.php.mercure.jwtSecret | b64enc | quote }}
  app_commonground_id: {{ .Values.security.commongroundId | b64enc | quote }}
